version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/url_short
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - BASE_URL=http://localhost:8080
      - REDIS=redis://redis:6379
    networks:
      - urlshortener-network
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=url_short
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - urlshortener-network
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

#For use when mysql is the preferred database of choice
#  db:
#    image: mysql:8
#    environment:
#      - MYSQL_DATABASE=your_database_name
#      - MYSQL_USER=your_username
#      - MYSQL_PASSWORD=your_password
#      - MYSQL_ROOT_PASSWORD=your_root_password
#    ports:
#      - '3306:3306'
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - urlshortener-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - urlshortener-network

volumes:
  postgres_data:

#volumes:
#  mysql_data:

networks:
  urlshortener-network: